### ISSUE TITLE
[Suggestion] dragon scale armor shouldn't break like and elytra

### ISSUE THREAD

**Issue by The-VoidX3** [GitPois1x/DragonLoot#9]
it would be cool and make it more unique if when Dragon scale armor broke it acted like and elytra and became useless until repaired instead of diapearing

**Comment by Globox1997** [comment]
In the coming update an elytra will be attached to the chestplate instead of just be included while crafting the plate.
Instead of just disappearing, an elytra will retain in the inventory [https://github.com/GitPois1x/DragonLoot/commit/bab6005fb7ddf33046bf9fba71953672afeaf13f](https://github.com/GitPois1x/DragonLoot/commit/bab6005fb7ddf33046bf9fba71953672afeaf13f)
